### ISSUE TITLE
Continuous circle of waiting

### ISSUE THREAD

**Issue by afrog4u2** [OfficeDev/microsoft-teams-apps-champion-management#23]
![teamschampionmgmt-circleofwait](https://user-images.githubusercontent.com/30191316/117668039-896e6180-b173-11eb-92c1-3b51d36432bd.png)

After installing the Champion Management app in Sharepoint and then sharing it to Teams, we have added it into a Team (more than one time and more than one Team) and all we get is a spinning circle - it never resolves whether in the Windows app or on the Teams website.  Removing it and readding it, nor recreating within a new team changes the response.  It will spin for hours.  

I have tried with both the admin (Global) account that the app was installed in and with a different user and no difference. 

The app installed with no errors.  

What should be my next step here?

**Comment by karuanag** [comment]
Thank you for reporting this.  We will see if we can reproduce.  Can I assume you are an owner of the team?  How many users are in this team or was this a test?  Please let us know any other technical details so we can resolve this for you. Thank you!

**Comment by afrog4u2** [comment]
I am the owner of the team and we had 7 users.

I used our primary global admin account to install the application.
This was my first time installing an application in Sharepoint, but it was
pretty straightforward.

Even after I shared the app to Teams, it took overnight before I could
actually see it in Teams. I did add it with my personal user (not global
admin) into one of our primary teams and got the spinning circle and it has
been over a week.
I dropped that tab off and then created a team and added all of the users
for our org and then made the global admin as an owner.

Logged in as the global admin, I then added the Champions Management to a
tab and then let it go spinning for about an hour before I reported it.

I have also found it to add as an application on the left side of the Teams
app and it does the same thing there.


Fletcher Gadsden
DATO Technologies

**Comment by afrog4u2** [comment]
The status is still showing Details Needed - is there something else that you need from me?

**Comment by eshwarmsft** [comment]
Hi @afrog4u2 

Perhaps we don't required more information would recommend you to please approve api permissions like this . Also look into the readme for the same.
![image](https://user-images.githubusercontent.com/69787520/118665262-cc81a200-b80f-11eb-952b-54bbe86d12f5.png)

**Comment by Smitat-msft** [comment]
Hi @afrog4u2 we fixed the issue in our latest code check-in.  Can you try it and confirm that your issue is fixed?

**Comment by purna429** [comment]
Hi Team,
I Installed the latest version (1.1) and I am also facing the same issue. Here are steps performed 
1.Installed the app to Tenant App catalog as a SharePoint admin the status shown "Deployed=Yes" and then Clicked on "Sync to Teams"
2. **Graph Pending requests **not appeared** in API Access section of SP Admin center**
3. Added the App to a teams channel as a Tab (using a service account which has teams and sp admin rights)
4. Its showing this error with a waiting circle like below
![404Error](https://user-images.githubusercontent.com/20446017/119880857-ab4d3f80-befa-11eb-9287-50e3efdebef2.png)

In the backend a site with url "**sites/ChampionManagementPlatform**" has been created.

Note :  Three days back on 05/24 installed the 1.0v app, found similar issues with error code 403 forbidden etc. Today I installed Version 1.1 and noticing the same issues. 

Any help would be appreciated.

Thanks
Purna

**Comment by Brammah121** [comment]
Hi, 

We are also seeing the same issue in V1.1.0
The app has been approved, synced to Teams and deployed with members added to the Sharepoint site created but we continue to see the loading screen within the Teams client 
![image](https://user-images.githubusercontent.com/82147341/120631063-5a3fcd00-c45f-11eb-93b4-56a567d17f8b.png)
I've removed the site and re-added just to make sure everything is setup correctly and it's still the same issue. 

Any help would be appreciated

Thanks

**Comment by mgh1066** [comment]
Is there any update to this issue please, I installed the app over a week ago and have been struggling with getting it working in both dev and prd 365 tenants.  

Continuous 'circle of waiting' every time after adding the app either in browser or teams desktop.  App deployment in SP, sync with teams, site creation all completes but after adding the app the quick start guide never gets built as previous posts

v, 1.1.0.0

Tried both on and off vpn, clients and browser (cache cleared)

Any advice would be appreciated

MGH

**Comment by eshwarmsft** [comment]
The issue is addressed in the Champion Management Portal 2.0, meanwhile would you please try to check the permission steps .
![image](https://user-images.githubusercontent.com/69787520/122505403-e8987f00-d019-11eb-982d-84af3f89e5ac.png)

**Comment by purna429** [comment]
@eshwarmsft , 
Thanks for the new version. My issue with 1.1 version was, on root site the "Member List" was not created in SharePoint site. I had to manually create the list .  Also I have faced couple of other permission issues, will post them soon with details.

-Purna

**Comment by mgh1066** [comment]
I cant find the new version 2.0
Grant permissions are correct and I've double checked. Definitely seems to be  permission related somewhere.  Even given full access to all users and same issue persists, spoken to MS support and they have been able to reproduce also and requested fiddler logs.

Thanks

**Comment by JoshLeporati** [comment]
@mgh1066 we are working on validating version 2.0 and plan on updating here soon! Thanks for your continued feedback here!

**Comment by v-saikirang** [comment]
Hi @purna429 , @afrog4u2 , @mgh1066 , @Brammah121

 Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@mgh1066 - I know you stated in another thread you were able to get loaded after 1.2 update.

@purna429 - with the v1.2 update we moved the member list creation to the same SPO site that the other assets are located on, so that should hopefully ease permissions and ability to deploy.

please do feel free to open new issue if still facing any other issues, thanks for using the solution!
