### ISSUE TITLE
Reinstalled with update but still getting spinning circle

### ISSUE THREAD

**Issue by Fuofgi** [OfficeDev/microsoft-teams-apps-champion-management#48]
Hello,

My team has been trying to install this, but ran into the spinning circle issue. I removed the app and downloaded the current version, but this remains unresolved. 
![Capture](https://user-images.githubusercontent.com/87829908/126694828-1230fe92-cc3e-4c6f-8af2-92076a114c5b.PNG)

I read through some of the other threads, and it's probably a permissions issue but my challenge is that there is no option to add 'Everyone except external users'. This group does not exist in my tenant. I tried adding a group that serves a similar purpose for my organization, but it made no difference. I'm a bit of a loss on where to go from here, so any advice is appreciated.

**Comment by v-saikirang** [comment]
Hi @Fuofgi , Thanks for trying this app. We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by Fuofgi** [comment]
When I did the reinstall yesterday, I went to 1.2, but the issue persists. I didn't blow away the site however. I'll look into repeating with that step.

**Comment by JoshLeporati** [comment]
Yes, make sure you remove site (and also remove it from deleted sites). Give ~15 minutes to ensure on reload it's not seeing a cached site of same name and please let us know results!

**Comment by maryha** [comment]
Hi, I installed the compiled package version 1.2 for the first time yesterday in 2 different tenants.  Both are showing the spinning circle and I'm seeing this error in the console:

> VM2608:formatted:1 Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at t.e.json (teams-web-part-application-assembly_en-us_6b6ebaa3ce70ed04f890e3a45d5c39a5.js:65)
    at clb-home-web-part_66c225f2edaa78bf3644dbf211a754d1.js:1

**Comment by v-saikirang** [comment]
Hi @maryha,

Thanks for trying this out. Few things:

1) Did you approve the Graph Permissions in the Share point tenant as specified in the ReadMe. Can you please share a screenshot of approved API Permissions.
2) Can you confirm if you have tenant admin rights.
3) If the API permissions are already approved and you have tenant admin rights can you refresh the app in your browser. 
4) If it still doesn't come up can you try uninstalling and reinstalling. Refer to the section "Upgrade to version 1.2.0.0" in [ReadMe](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/README.md). Please note that you have to wait for 15 minutes after step 4 and start over the the installation as per the section "Deploy your Package to SharePoint".
5) If you still see any issue can you please share a screenshot of the console messages.

Thanks.

**Comment by maryha** [comment]
Hi @v-saikirang, 

1. I have granted permissions:
<img width="929" alt="AppPermissions" src="https://user-images.githubusercontent.com/7673459/127381576-c0d93afe-be61-48d3-aa04-2689f6573024.png">

2. I am a global admin.
3. Refresh had no change
4. Reinstalled version 1.2 (which I had installed in the first place)
5. Still getting spinning circle.
6. Here is an image of the console errors:
<img width="824" alt="ChampConsoleErrors" src="https://user-images.githubusercontent.com/7673459/127381780-e19e1aea-900d-4c11-b35e-42bff0dd910c.png">

**Comment by v-saikirang** [comment]
Hi @maryha ,

Thanks for your patience.

1)Can you please click on a 404 error and a 500 error in the console and share screenshots of the details.
2) can you check if "ChampionManagementPlatform" site collection is created. If yes, can you share a screenshot of the site contents page.
3) If the above site exists can you delete it from both Active and Deleted sites, delete the app in teams, wait for 15 mins, "sync to teams" from the app catalog and install the app again.

Thanks.

**Comment by l2marsha** [comment]
Hi,
after deleting v1.1.0.0 and installing 1.2.0.0 i am still getting the same issue also. any assistance would be appreciated
![image](https://user-images.githubusercontent.com/88155490/127526824-9cca62b1-d680-4d01-8573-28967bf71349.png)

**Comment by maryha** [comment]
Hi @v-saikirang,

I'll work on getting you the details of the 404 and 500 errors, but the ChampionManagementPlatform is never created.  Is there something wrong with the site template json perhaps?  Hence the json error?

Mary

**Comment by v-saikirang** [comment]
Hi @maryha, No there is nothing wrong with site template json. It was thoroughly tested. It looks there was an issue with Graph API call. Most of the times it would be resolve if you try after some time. Please follow the instructions in my previous message and let me know if it works. Thanks.

**Comment by nishants-22** [comment]
@JoshLeporati, @v-saikirang same issue as @maryha. Upgrading from v1: It keeps spinning on Teams side and ChampionManagementPlatform site is never created. Have tried a few times now.

**Comment by v-saikirang** [comment]
Hi @nishants-22,

Please wait for 15 minutes after you have completed first 4 steps under the section "Upgrade to version 1.2.0.0" in ReadMe document and then restart the installation. Make sure the site is also not under Deleted sites in admin portal. And can you please try this in browser so we can check the console for any errors logged. Can you also please share screenshots of the API permissions page and console errors if any. 

Thanks.

**Comment by maryha** [comment]
Hi @v-saikirang,

Did all of the above - deleted the app.  Made sure the champions site did not exist (never created).  I'm attaching a document with all my steps and screenshots.

Regards,
Mary
[ChampionsProgramBug.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6909234/ChampionsProgramBug.docx)

**Comment by v-saikirang** [comment]
Hi @maryha , Thanks for the detailed document. It looks an issue with Graph API from your domain. I would like to confirm if  you are able to get results from graph API. I have detailed the steps in the attached document. Can you please try and let us know. Thanks
[Graph api steps.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6921475/Graph.api.steps.docx)

**Comment by nishants-22** [comment]
@v-saikirang I'm sure I have followed all instructions diligently. Have tried this at least 5 times now giving with a gap of 15 mins to 48 hours. Upgrade process is simply broken and the champs SharePoint site never gets provisioned. You may want to test it in a fresh environment rather than your dev environment.

**Comment by v-saikirang** [comment]
Hi @nishants-22, 
Sorry for your experience. We have tried and tested this in multiple new tenants so far. We have also seen this updated for few other clients as well. Can you please try in a browser and share a screenshot of the console error logs. Can you also share screenshots of your API permissions page in Share point tenant admin. Thanks.

**Comment by maryha** [comment]
Hi @v-saikirang, I did as you requested to run the site search via Graph Explorer.  That is reporting a 500 error as well.  I wonder if it has anything to do with being a "dev" tenant or "first release" tenant.  I am getting the error in both tenants that are first release. But a colleague was able to get it running in a production tenant.

Document with screenshots: 
[GraphExplorerTesting.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6924389/GraphExplorerTesting.docx)

**Comment by nishants-22** [comment]
@v-saikirang I've attached the document with screenshot of the console error log, screenshot of API permissions page, Graph API Success, Screenshot of missing (not provisioned) Champs site. Note, console error is a 404 error for ChampionManagementPlatform/_api/web/lists/GetByTitle('Member%20List') - likely because the ChampionManagementPlatform site is not getting provisioned.
[ConsoleErrorLogsAPIPermissionsGraphAPISuccess.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6925596/ConsoleErrorLogsAPIPermissionsGraphAPISuccess.docx)

**Comment by maryha** [comment]
@v-saikirang - to confirm nishants-22's experience, in my other tenant, the https://graph.microsoft.com/v1.0/sites?search=* query works fine in Graph Explorer (and in the network trace when the tab is added), but the site is never provisioned.

Mary

**Comment by v-saikirang** [comment]
Hi @maryha, 
You mentioned the graph api was not working in both tenants. So is this the third tenant that you are talking about.
Hi @nishants-22 , we will review and get back to you as soon as we can.
Thanks.

**Comment by maryha** [comment]
@v-saikirang, no, I was mistaken before.  The Graph API call (sites/search=*) is actually working in one of my two "demo" tenants, but not the other.  Sorry for the misdirection.  The championsmanagement site does not get created in either.

**Comment by v-saikirang** [comment]
Hi @maryha ,
Can you please share a screenshot of the graph results page. Thanks.

**Comment by maryha** [comment]
@v-saikirang - Here you go! 
![image](https://user-images.githubusercontent.com/7673459/128059470-9feb8fcf-3b65-4f96-b4d9-46b59cc5d091.png)

**Comment by v-saikirang** [comment]
Hi @nishants-22,
Can you please confirm if CMP site is not under "Deleted Sites". Can you please share a screenshot.
![image](https://user-images.githubusercontent.com/87538202/128135719-f11f8b96-fd85-4616-ab0d-fcd0997ba00c.png)
 And may i know if you are using a personal MS account or work account. And are you using a demo tenant?
Thanks.

**Comment by v-saikirang** [comment]
Hi @maryha,
Thanks for your patience.
May I know if you are using personal or work account and tenant type. And can you please try re installing the app in the tenant where the graph api worked. Please make sure the site is under Active or Deleted sites. And please share the console logs again. Thanks.

**Comment by nishants-22** [comment]
@v-saikirang attached a screenshot confirming the CMP site is not under Deleted Sites. I'm using a demo tenant and work account (demo tenant's global admin account).
![SPODeletedSitesScreenshot](https://user-images.githubusercontent.com/88203887/128185889-01f552a5-b191-4610-bd90-bb1bb1e705fb.jpg)

**Comment by v-saikirang** [comment]
Hi @nishants-22 ,

Can you please check if "Member list" list is present under your root SharePoint site.
Thanks.

**Comment by nishants-22** [comment]
Its not.
![SPODeletedSitesScreenshot](https://user-images.githubusercontent.com/88203887/128187162-72dceba9-b86d-46eb-89a7-f9d06e8664dc.jpg)

**Comment by v-saikirang** [comment]
Hi @nishants-22 ,
May I know if you are available for a Teams call so we can trouble shoot this issue. If yes, please share your email and preferred timings. I can share an invite. Please note that we are on IST. So we can work on a suitable time for both of us.
Thanks.

**Comment by v-saikirang** [comment]
Hi @maryha,
Were you able to try re install on the tenant where graph api is working as per my last comment. Please let us know the outcome and we can decide on next steps accordingly.
Thanks.

**Comment by nishants-22** [comment]
Thanks @v-saikirang, I'll reach out to you.

**Comment by maryha** [comment]
@v-saikirang, sorry, I was caught up in project work yesterday.  I did the reinstall where the Graph API search call is working.  But the site does not get created.  Something is breaking before it gets there:

Screen shots:
[Champions Issue Tenant 2 Screenshots.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6939054/Champions.Issue.Tenant.2.Screenshots.docx)

**Comment by v-saikirang** [comment]
Hi @maryha,

May I know if you are available for a Teams call so we can trouble shoot your issue. If yes, please share your email and preferred timings. I work on IST and we can work out a suitable time.
Thanks.

**Comment by maryha** [comment]
Hi @v-saikirang , I have availability tomorrow morning EST.  Is 9:30 or 10 am EST okay for you?

Thanks

**Comment by Aalkfk** [comment]
Hey everybody,

Did you find a solution yet?
If you still need someone to test, we've got the same bug in our testing environment.

**Comment by v-saikirang** [comment]
Hi @Aalkfk,

Can you please share more details about the issues you are facing. Please share all the steps followed and screenshots as needed.
Thanks.

**Comment by Aalkfk** [comment]
Good morning @v-saikirang,

sorry for the late response.
What we did:
1. app uploaded & released (Global Admin).
2. set permissions for graph
3. app included in teams and opened as admin.
4. deleted everything (app, there was no site) and started again with step 1.

Problem:
Only the leaderboard is displayed in the app window and the app takes forever to load. 
There is also no SharePoint site displayed in the background.

Everything was done in the demo environment (default language: English) with a Global Admin.
We are dealing with a fresh install, not an update. :-)

**Comment by v-saikirang** [comment]
Hi @Aalkfk,

1) Can you try in a browser and share a screenshot of the console logs 
2) Can you perform the steps as mentioned in the document to make sure you are able to access Graph API 
[Graph api steps.docx](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/6967451/Graph.api.steps.docx)
Thanks.

**Comment by Aalkfk** [comment]
Hey @v-saikirang,

sorry for the late response.
Here's the console output:
![image](https://user-images.githubusercontent.com/55743509/129526647-f0511ae9-995c-4c68-8005-53b036bd6078.png)

Screen of Graph API:
![image](https://user-images.githubusercontent.com/55743509/129527658-736e10f5-3c5e-4c5c-b902-df462c3a1fea.png)

> `{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": [
        {
            "createdDateTime": "2019-12-04T12:25:03Z",
            "id": "m365x786936.sharepoint.com,3e923803-267c-408f-8224-ddb7f54521dd,6ef77925-d849-44fd-b7fc-103903a592af",
            "lastModifiedDateTime": "2021-06-23T12:05:22Z",
            "name": "m365x786936.sharepoint.com",
            "webUrl": "https://m365x786936.sharepoint.com",
            "displayName": "Communication site",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2020-03-20T20:21:27Z",
            "id": "m365x786936.sharepoint.com,3234377f-1370-40ce-bb6c-f04a5907e2f9,0a9d26a9-2a5b-4025-b075-1c7c52cb9c8f",
            "lastModifiedDateTime": "2020-03-08T12:36:12Z",
            "name": "TestTeams",
            "webUrl": "https://m365x786936.sharepoint.com/sites/TestTeams",
            "displayName": "Test Teams",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2021-05-17T06:04:20Z",
            "id": "m365x786936.sharepoint.com,c74d3bb3-6dc4-48cc-a99e-047466cc4c23,13e0e36d-2d30-431d-ad46-043201a1c7fc",
            "lastModifiedDateTime": "2021-05-09T07:50:28Z",
            "name": "PowerShellTest",
            "webUrl": "https://m365x786936.sharepoint.com/sites/PowerShellTest",
            "displayName": "Test Team",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2021-06-15T06:51:10Z",
            "id": "m365x786936.sharepoint.com,b07c6832-ccfd-45d0-9090-082f93b5c373,24206e65-8991-4712-8930-c47c4194c209",
            "lastModifiedDateTime": "2021-05-30T06:07:10Z",
            "name": "Unternehmens-Wiki",
            "webUrl": "https://m365x786936.sharepoint.com/sites/Unternehmens-Wiki",
            "displayName": "Unternehmens-Wiki",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2021-06-15T07:11:59Z",
            "description": "Team Wiki0721",
            "id": "m365x786936.sharepoint.com,4121ed29-1bed-4f11-8921-36a29ee9182f,ad7196ac-7641-415c-aed9-62aff7e6937f",
            "lastModifiedDateTime": "2021-05-30T05:51:22Z",
            "name": "TeamWiki0721",
            "webUrl": "https://m365x786936.sharepoint.com/sites/TeamWiki0721",
            "displayName": "Team Wiki0721",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2021-03-02T07:30:41Z",
            "id": "m365x786936.sharepoint.com,3312c22d-613f-44e0-b7e9-7b84ac1cafbd,fbcd065e-88e7-4199-ad58-a95090ce3047",
            "lastModifiedDateTime": "2021-03-02T07:30:38Z",
            "name": "Store",
            "webUrl": "https://m365x786936.sharepoint.com/sites/Store",
            "displayName": "Default-Store",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2020-07-03T12:40:14Z",
            "id": "m365x786936.sharepoint.com,b6c9bf95-1c04-43ca-8874-9cc07ff89ceb,d2de4e36-99e5-44bb-9698-a3e292f9a007",
            "lastModifiedDateTime": "2020-06-21T05:43:04Z",
            "name": "AllCompany.14589526016.kdelfaqp",
            "webUrl": "https://m365x786936.sharepoint.com/sites/AllCompany.14589526016.kdelfaqp",
            "displayName": "All Company",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2019-12-04T12:28:27Z",
            "id": "m365x786936.sharepoint.com,f234959d-8b38-4751-8fc1-86e58def9a8f,1e9cac80-dc5f-4ab5-90dc-18ea03fae415",
            "lastModifiedDateTime": "0001-01-01T08:00:00Z",
            "name": "hub",
            "webUrl": "https://m365x786936.sharepoint.com/portals/hub",
            "displayName": "PointPublishing Hub Site",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "2019-12-04T12:30:13Z",
            "id": "m365x786936.sharepoint.com,7a6025ec-d56e-421c-a551-cf924da473c0,397c055b-41f8-415a-8dd2-719a9a4f4b2b",
            "lastModifiedDateTime": "0001-01-01T08:00:00Z",
            "name": "Community",
            "webUrl": "https://m365x786936.sharepoint.com/portals/Community",
            "displayName": "Community",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,b6c9bf95-1c04-43ca-8874-9cc07ff89ceb,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2021-02-22T05:49:13Z",
            "name": "AllCompany.14589526016.kdelfaqp",
            "webUrl": "https://m365x786936.sharepoint.com/sites/AllCompany.14589526016.kdelfaqp",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,f234959d-8b38-4751-8fc1-86e58def9a8f,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2021-01-21T10:22:07Z",
            "name": "hub",
            "webUrl": "https://m365x786936.sharepoint.com/portals/hub",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,b87eb755-99b0-43f1-99f4-f29ae5e65928,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2020-10-18T04:48:19Z",
            "name": "search",
            "webUrl": "https://m365x786936.sharepoint.com/search",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,358ed906-ce62-4096-9e06-84e24af91d32,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2020-10-18T04:48:19Z",
            "name": "ReportAdmins",
            "webUrl": "https://m365x786936.sharepoint.com/sites/ReportAdmins",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,7a6025ec-d56e-421c-a551-cf924da473c0,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2020-10-18T04:48:19Z",
            "name": "Community",
            "webUrl": "https://m365x786936.sharepoint.com/portals/Community",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        },
        {
            "createdDateTime": "0001-01-01T08:00:00Z",
            "id": "m365x786936.sharepoint.com,a8140924-8859-45df-85d3-6d5b2e17010a,00000000-0000-0000-0000-000000000000",
            "lastModifiedDateTime": "2020-10-18T04:48:19Z",
            "name": "contentTypeHub",
            "webUrl": "https://m365x786936.sharepoint.com/sites/contentTypeHub",
            "root": {},
            "siteCollection": {
                "hostname": "m365x786936.sharepoint.com"
            }
        }
    ]
}`

**Comment by v-saikirang** [comment]
Hi @Aalkfk,

Please let me know if you are available for a Teams call. If yes, please share you email id.

Thanks.

**Comment by Aalkfk** [comment]
Hey @v-saikirang 
my e-mail is joshua.wolf@zeag-energie.de

**Comment by Fuofgi** [comment]
So unfortunately I had to wait some time to get the SharePoint site deleted due to a retention policy that was rolled out, but the good news is that after completed removing the site, app, and graph permissions and then readding them, I was able to get rid of the spinning circle. I did have to load the team in the browser to get it to add me though.

One last query before I close this off. My tenant does not have a group called 'Everyone except external users'. I'm using an all active users group we made instead. I'm assuming this isn't an issue?

**Comment by JoshLeporati** [comment]
@Fuofgi - that's great news! The use of any group is fine, we recommend everyone due to how the program is generally run and to expose the champions list to anyone in org to access. Using another AD group with all active users accomplishes the same thing and would not be an issue. The only thing to remember is if a user attempts to load the solution and is not either in that AD group, or at some point you look at a more restrictive group - that's the usual cause for others receiving a blue spinning wheel (no access).
